### ISSUE TITLE
Dockerize for self-hosting

### ISSUE THREAD

**Issue by accforgithubtest** [MarsHeer/offtiktokapi#1]
Looks like a interesting project and thank you for creating it !

Can you please dockerize it ? Makes it a hundred times easier to self-host alongside many other docker applications.
I would suggest a single docker container that has both the front end and back-end in a single image, if that is possible.

**Comment by MarsHeer** [comment]
@accforgithubtest I've just dockerized each container individually.

There are some quirks to merging them into a monorepo and holding them in an single image that I haven't gotten around to resolving yet, but will hopefully get it done in the future :)
